[package]
name = "readingroom-providers"
version = "0.1.0"
edition = "2021"

[dependencies]
readingroom-core = { path = "../core" }

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
reqwest.workspace = true
tracing.workspace = true
async-trait.workspace = true
thiserror.workspace = true
chrono.workspace = true
quick-xml = "0.41"
