// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/activity";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/activity")>;
      $$route?: undefined;
    },
    {
      path: "/authors";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/authors")>;
      $$route?: undefined;
    },
    {
      path: "/books";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/books")>;
      $$route?: undefined;
    },
    {
      path: "/calendar";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/calendar")>;
      $$route?: undefined;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/index")>;
      $$route?: undefined;
    },
    {
      path: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/login")>;
      $$route?: undefined;
    },
    {
      path: "/queue";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/queue")>;
      $$route?: undefined;
    },
    {
      path: "/settings";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings")>;
      $$route?: undefined;
    },
    {
      path: "/wanted";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/wanted")>;
      $$route?: undefined;
    },
    {
      path: "/authors/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/authors/[id]")>;
      $$route?: undefined;
    },
    {
      path: "/books/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/books/[id]")>;
      $$route?: undefined;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/index")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/books";
      id: "/books";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/books")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/:id";
          id: "/:id";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/books/[id]")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/login";
      id: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/login")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/queue";
      id: "/queue";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/queue")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/wanted";
      id: "/wanted";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/wanted")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/authors";
      id: "/authors";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/authors")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/:id";
          id: "/:id";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/authors/[id]")>;
          $$route?: undefined;
          children?: undefined;
        }
      ];
    },
    {
      path: "/activity";
      id: "/activity";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/activity")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/calendar";
      id: "/calendar";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/calendar")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/settings";
      id: "/settings";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings")>;
      $$route?: undefined;
      children?: undefined;
    }
  ];
}
