// Generated by filesystem-routing. Do not edit.
// Regenerated whenever a route file is added, changed or removed.

declare module "virtual:file-routes" {
  /** A code-split ref: the delivery adapter emits it as a dynamic import. */
  export interface FileRouteLazyRef<M = Record<string, unknown>> {
    src: string;
    import(): Promise<M>;
  }

  /** An eager ref: its picked exports are imported statically. */
  export interface FileRouteEagerRef<M = Record<string, unknown>> {
    /** The source module path — present when the convention emitted the ref lazy and `codeSplitting: false` delivered it eagerly. */
    src?: string;
    require(): M;
  }

  /** A flat entry of the route manifest. */
  export interface FileRouteEntry {
    path: string;
    page?: boolean;
    $component?: FileRouteLazyRef<any> | FileRouteEagerRef<any>;
    $$route?: FileRouteEagerRef<any>;
    [key: string]: unknown;
  }

  /** An entry of the nested `pageRoutes` view. */
  export interface FileRouteTreeEntry extends FileRouteEntry {
    id: string;
    children?: readonly FileRouteTreeEntry[];
  }

  /** The flat route manifest, in scan order. */
  const routes: readonly [
    {
      path: "/activity";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/activity")>;
      $$route: FileRouteEagerRef<typeof import("./routes/activity")>;
    },
    {
      path: "/authors";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/authors")>;
      $$route?: undefined;
    },
    {
      path: "/books";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/books")>;
      $$route?: undefined;
    },
    {
      path: "/calendar";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/calendar")>;
      $$route: FileRouteEagerRef<typeof import("./routes/calendar")>;
    },
    {
      path: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/index")>;
      $$route: FileRouteEagerRef<typeof import("./routes/index")>;
    },
    {
      path: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/login")>;
      $$route?: undefined;
    },
    {
      path: "/queue";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/queue")>;
      $$route: FileRouteEagerRef<typeof import("./routes/queue")>;
    },
    {
      path: "/settings";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings")>;
      $$route: FileRouteEagerRef<typeof import("./routes/settings")>;
    },
    {
      path: "/wanted";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/wanted")>;
      $$route: FileRouteEagerRef<typeof import("./routes/wanted")>;
    },
    {
      path: "/authors/:id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/authors/[id]")>;
      $$route: FileRouteEagerRef<typeof import("./routes/authors/[id]")>;
    },
    {
      path: "/authors/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/authors/index")>;
      $$route: FileRouteEagerRef<typeof import("./routes/authors/index")>;
    },
    {
      path: "/books/*id";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/books/[...id]")>;
      $$route: FileRouteEagerRef<typeof import("./routes/books/[...id]")>;
    },
    {
      path: "/books/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/books/index")>;
      $$route: FileRouteEagerRef<typeof import("./routes/books/index")>;
    },
    {
      path: "/settings/account";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings/account")>;
      $$route: FileRouteEagerRef<typeof import("./routes/settings/account")>;
    },
    {
      path: "/settings/clients";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings/clients")>;
      $$route: FileRouteEagerRef<typeof import("./routes/settings/clients")>;
    },
    {
      path: "/settings/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings/index")>;
      $$route: FileRouteEagerRef<typeof import("./routes/settings/index")>;
    },
    {
      path: "/settings/indexers";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings/indexers")>;
      $$route: FileRouteEagerRef<typeof import("./routes/settings/indexers")>;
    },
    {
      path: "/settings/integrations";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings/integrations")>;
      $$route: FileRouteEagerRef<typeof import("./routes/settings/integrations")>;
    },
    {
      path: "/settings/library";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings/library")>;
      $$route: FileRouteEagerRef<typeof import("./routes/settings/library")>;
    },
    {
      path: "/settings/metadata";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings/metadata")>;
      $$route: FileRouteEagerRef<typeof import("./routes/settings/metadata")>;
    },
    {
      path: "/settings/notifications";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings/notifications")>;
      $$route: FileRouteEagerRef<typeof import("./routes/settings/notifications")>;
    }
  ];
  export default routes;

  /** The page entries, nested by path with grouping segments stripped. */
  export const pageRoutes: readonly [
    {
      path: "/";
      id: "/";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/index")>;
      $$route: FileRouteEagerRef<typeof import("./routes/index")>;
      children?: undefined;
    },
    {
      path: "/books";
      id: "/books";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/books")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/books/index")>;
          $$route: FileRouteEagerRef<typeof import("./routes/books/index")>;
          children?: undefined;
        },
        {
          path: "/*id";
          id: "/*id";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/books/[...id]")>;
          $$route: FileRouteEagerRef<typeof import("./routes/books/[...id]")>;
          children?: undefined;
        }
      ];
    },
    {
      path: "/login";
      id: "/login";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/login")>;
      $$route?: undefined;
      children?: undefined;
    },
    {
      path: "/queue";
      id: "/queue";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/queue")>;
      $$route: FileRouteEagerRef<typeof import("./routes/queue")>;
      children?: undefined;
    },
    {
      path: "/wanted";
      id: "/wanted";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/wanted")>;
      $$route: FileRouteEagerRef<typeof import("./routes/wanted")>;
      children?: undefined;
    },
    {
      path: "/authors";
      id: "/authors";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/authors")>;
      $$route?: undefined;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/authors/index")>;
          $$route: FileRouteEagerRef<typeof import("./routes/authors/index")>;
          children?: undefined;
        },
        {
          path: "/:id";
          id: "/:id";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/authors/[id]")>;
          $$route: FileRouteEagerRef<typeof import("./routes/authors/[id]")>;
          children?: undefined;
        }
      ];
    },
    {
      path: "/activity";
      id: "/activity";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/activity")>;
      $$route: FileRouteEagerRef<typeof import("./routes/activity")>;
      children?: undefined;
    },
    {
      path: "/calendar";
      id: "/calendar";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/calendar")>;
      $$route: FileRouteEagerRef<typeof import("./routes/calendar")>;
      children?: undefined;
    },
    {
      path: "/settings";
      id: "/settings";
      page: true;
      $component: FileRouteLazyRef<typeof import("./routes/settings")>;
      $$route: FileRouteEagerRef<typeof import("./routes/settings")>;
      children: readonly [
        {
          path: "/";
          id: "/";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/settings/index")>;
          $$route: FileRouteEagerRef<typeof import("./routes/settings/index")>;
          children?: undefined;
        },
        {
          path: "/account";
          id: "/account";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/settings/account")>;
          $$route: FileRouteEagerRef<typeof import("./routes/settings/account")>;
          children?: undefined;
        },
        {
          path: "/clients";
          id: "/clients";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/settings/clients")>;
          $$route: FileRouteEagerRef<typeof import("./routes/settings/clients")>;
          children?: undefined;
        },
        {
          path: "/library";
          id: "/library";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/settings/library")>;
          $$route: FileRouteEagerRef<typeof import("./routes/settings/library")>;
          children?: undefined;
        },
        {
          path: "/indexers";
          id: "/indexers";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/settings/indexers")>;
          $$route: FileRouteEagerRef<typeof import("./routes/settings/indexers")>;
          children?: undefined;
        },
        {
          path: "/metadata";
          id: "/metadata";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/settings/metadata")>;
          $$route: FileRouteEagerRef<typeof import("./routes/settings/metadata")>;
          children?: undefined;
        },
        {
          path: "/integrations";
          id: "/integrations";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/settings/integrations")>;
          $$route: FileRouteEagerRef<typeof import("./routes/settings/integrations")>;
          children?: undefined;
        },
        {
          path: "/notifications";
          id: "/notifications";
          page: true;
          $component: FileRouteLazyRef<typeof import("./routes/settings/notifications")>;
          $$route: FileRouteEagerRef<typeof import("./routes/settings/notifications")>;
          children?: undefined;
        }
      ];
    }
  ];
}
